### ISSUE TITLE
Unable to use bitpay on Magento 2 2.1.4

### ISSUE THREAD

**Issue by j0e1an** [bitpay/magento2-plugin#10]
Magento 2 version: 2.1.4

Procedure: in Store - Configuration - Sales- payment method -bitpay - pairing code, generated a pairing code from bitpay.com. 

Expectation: After click on "save" to save settings, if pairing success, user can see bitpay as a payment method on checkout, if pairing fails, admin can see an error message on the configuration page.

Result: After click on save nothing is processed or saved, no error message and the pairing code is not saved after refreshing the page.

**Comment by pieterpoorthuis** [comment]
Can you enable logging (in the Magento plugin settings) and provide the logs from var/log/payment_bitpay.log ?

**Comment by pieterpoorthuis** [comment]
Another question: do you have php-mcrypt enabled in your Apache?

**Comment by pieterpoorthuis** [comment]
Open too long without activity. Closing.
