### ISSUE TITLE
no Magento Connect in System ( or anywhere ) Ver 2.1.6

### ISSUE THREAD

**Issue by squareborg** [bitpay/magento2-plugin#18]
I'm using Magento ver. `2.1.6`  and in the GUIDE it says 

> Once you have the key, log into you Magento Store's Admin Panel and navigate to System > Magento Connect > Magento Connect Manager.

However there is no Magento Connect in System ( or anywhere )

Am I missing something?

**Comment by pieterpoorthuis** [comment]
The plugin is not yet available in Magento Connect. I've updated the README file to reflect this.
